### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by farnaf** [AAP127/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
  - the fix in the screenshot doesn't really fix the issue of returning an empty list
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2
  - [new link)(https://google.com) is a valid input (i.e. valid content in a markdown file), it shouldn't throw an exception, instead return an empty list with no links, interpreted as no links existing in the md file

**Bug/Input 3** - same feedback as bug/input 2. I suggest focusing on another bug you fixed or showing what attempts you made at making the program return the correct output
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
nice job 😃 
Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by AAP127** [comment]
Hi, I had a couple of questions regarding my report and the rubric.

-When referring to the screenshot for issue 2, my intention with that fix was to prevent double output, so does the comment mean that the program should be returning an empty list instead?

-In our lab group we had decided that files like test-file2.md (in a format other than [text] (link) ) should throw an exception, due to having incorrect structure; should I instead change the program to just return an empty list if the formatting is invalid (as in if it it is at all different from the structure [text] (link) )?

-Also, if a file were to be in the correct bracket/parenthesis structure, but then not actually be a link (say the input is like [Website] (google) ), would the expectation also be that the program just returns an empty list?

Thank you!

**Comment by farnaf** [comment]
Hi there! 
- Yes, so the main goal is to have your program return a correct output (i.e. ArrayList with correct links). If you initially get double outputs, see how to avoid the program from adding link strings to the list twice, rather than considering the input wrong 
- Ah I see. 
  The java program is defined to take **any** Markdown file as input, and then output list of all the URLs that're formatted as links inside the input file. Based on the program specification, there's no invalid input (unless some other file than .md is passed in as the argument). An empty output list means no links were found - which is the case when we have `[text] (link)` due to the space in between the closed bracket and open paren
- This a great test case! I'd say in this case "google" is a valid link. If you create a .md file and put `[Website](google)` in it and preview it, you'll notice `Website` becomes a Markdown URL. 
  - my advice in cases where you're not entirely sure if a test case is a "valid" link is to test it out with a markdown file (I personally use https://dillinger.io/). If the file showed it as a link, then you can consider it valid

Let me know if you have any other questions!

**Comment by AAP127** [comment]
Thank you for the clarification on those points! 

I had just one more question about the last part. In this context of discussing a link to be "valid" does that just mean that it is in the format of a link, regardless of it actually takes me to a working/ meaningfully usable webpage? For example, if I were to use 
 "[ ] (google)"  (without the space between brackets and parenthesis, just added that so GitHub would actually show it)  as a test case, having any text between the [brackets] would create a link which takes me somewhere (even if this is just my website/google which is just a 404). I just wanted to confirm that this would still be treated as a valid link, and that I use text between the brackets to determine validity. 
 
 Thank you again!

**Comment by farnaf** [comment]
Yep correct!

If you want your program to verify whether the formatted link is actually a valid link, that'd be super awesome (but beyond what we're looking for)

**Comment by AAP127** [comment]
Thank you so much for the help on the report!
